experiment:
  project: bar_fsq
  name: bar_fsq_16bits
  output_dir: bar_fsq_16bits
  max_train_examples: 1281167
  save_every: 25000
  eval_every: 25000
  generate_every: 5000
  log_every: 50
  log_grad_norm_every: 1000
  resume: true
  logging_dir: bar_fsq_16bits/logs

model:
  vq_model:
    codebook_size: 65536
    token_size: 16
    encoder_lr_mult: 0.1
    clip_align_layer_id: 2
    use_checkpoint: false
    vit_dec_patch_size: 16
  discriminator:
    dino_ckpt_path: assets/models/dino_vit_small_patch8_224.pth
    norm_type: bn

losses:
  discriminator_start: 100000
  discriminator_factor: 1.0
  discriminator_weight: 0.05
  perceptual_loss: lpips-convnext_s-1.0-0.1
  perceptual_weight: 1.1
  reconstruction_weight_l1: 0.1
  reconstruction_weight_l2: 1.0
  clip_loss_weight: 0.7
  gram_loss_weight: 10.0

dataset:
  params:
    train_shards_path_or_url: /path/to/imagenet-train-{000000..000320}.tar
    eval_shards_path_or_url: /path/to/imagenet-val-{000000..000049}.tar
    num_workers_per_gpu: 16
  preprocessing:
    resize_shorter_edge: 256
    crop_size: 256
    random_crop: true
    random_flip: true

optimizer:
  name: adamw
  params:
    learning_rate: 0.0001
    discriminator_learning_rate: ${optimizer.params.learning_rate}
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.0

lr_scheduler:
  scheduler: cosine
  params:
    learning_rate: ${optimizer.params.learning_rate}
    warmup_steps: 10000
    end_lr: 1.0e-05

training:
  compile_model: true
  gradient_accumulation_steps: 1
  per_gpu_batch_size: 32
  mixed_precision: bf16
  enable_tf32: true
  use_ema: true
  seed: 42
  max_train_steps: 200000
  num_generated_images: 2
  max_grad_norm: 1.0
  enable_wandb: true
